<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Welcome Back</name>
   <tag></tag>
   <elementGuidId>0a0cfd64-bd6a-46c1-a548-a7c281635b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/main/section/div/div/div/div/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Welcome Back!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1731d5fb-27ea-4877-b13a-ba1c9df21166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary</value>
      <webElementGuid>ae0d462f-333d-4fe4-8cab-9b81b20e63e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome Back!</value>
      <webElementGuid>73cdf06b-498a-4024-bf14-e5fc5d101a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/main[1]/section[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row justify-content-center g-0&quot;]/div[@class=&quot;col-lg-9 d-flex justify-content-center&quot;]/div[@class=&quot;account-page&quot;]/div[1]/h2[@class=&quot;text-primary&quot;]</value>
      <webElementGuid>61fd3932-9d87-48ff-9775-403fd6aefaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/main/section/div/div/div/div/div/div/div/h2</value>
      <webElementGuid>567e6c1f-a6b5-4075-8ba4-9149d41c8987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[2]/following::h2[1]</value>
      <webElementGuid>cbae3177-67e8-4f52-895f-b7a695ed4827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[2]/following::h2[1]</value>
      <webElementGuid>5a7f2dd7-0bc6-4f2f-be90-870aab6dfd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome Back!']/parent::*</value>
      <webElementGuid>15e8fcaf-bef7-4af1-b547-f2f66fa40ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>4bd7554e-fa05-4f19-bb65-1f245ce85031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Welcome Back!' or . = 'Welcome Back!')]</value>
      <webElementGuid>c2ae905c-4101-4922-8a2c-1271ec7dcab4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
