<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Support Policy_ri-user-3-line fs-22</name>
   <tag></tag>
   <elementGuidId>76993a16-d2d7-4edf-9e24-92cf90ed99d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-user-3-line.fs-22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='page-header-user-dropdown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7b9851c1-883d-4384-9df5-472824c0d192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> ri-user-3-line fs-22</value>
      <webElementGuid>70f91cca-8f4f-4b7e-86f8-0e277545f24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header-user-dropdown&quot;)/i[@class=&quot;ri-user-3-line fs-22&quot;]</value>
      <webElementGuid>29c96808-62a9-4a92-90db-63e9c84acfe1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='page-header-user-dropdown']/i</value>
      <webElementGuid>700f2622-e36c-4a1c-8574-29ac07714f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/i</value>
      <webElementGuid>79b7067b-d41c-4770-9d11-e7ab2cf5d3f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
